project_id = "mkcgkfzltohxagqvsbqk"

[auth]
site_url = "https://turuturustars.co.ke"
additional_redirect_urls = ["https://turuturustars.co.ke/auth/callback", "https://turuturustars.co.ke/dashboard", "https://turuturustars.co.ke/reset-password"]

[functions.mpesa]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.mpesa-confirmation]
verify_jwt = false

[functions.mpesa-validation]
verify_jwt = false

[functions.cloudinary-upload]
verify_jwt = false

[functions.twilio-verify]
verify_jwt = false
 
 [functions.send-verification-email]
 verify_jwt = false
 
[functions.create-profile]
 verify_jwt = false

[functions.jobs-ingest]
verify_jwt = false

[functions.jobs-scrape]
verify_jwt = false

[functions.stk-push]
verify_jwt = true

[functions.stk-callback]
verify_jwt = false

[functions.till-submit]
verify_jwt = true

[functions.verify-till]
verify_jwt = true

[functions.approve-payment]
verify_jwt = true

[functions.pesapal]
verify_jwt = false

[functions.pesapal-ipn]
verify_jwt = false

[functions.admin-ops]
verify_jwt = true
